name: Trigger Automation

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Private Repo
        run: |
          curl -X POST https://api.github.com/repos/QATestingGit/Robot-Framework/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -d '{"event_type":"run-tests"}'
      - name: Push Results to Portal Repo
        run: |
          git clone https://x-access-token:${{ secrets.PORTAL_PAT }}@github.com/QATestingGit/automation-portal.git
          cp -r results/* automation-portal/results/
          cd automation-portal
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update test results"
          git push
