name: Trigger Automation

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Private Repo
        run: |
          curl -X POST https://api.github.com/repos/<QATestingGit>/Robot-Framework/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -d '{"event_type":"run-tests"}'
